#!/bin/bash

if git diff --cached --name-only | grep "^docs/" > /dev/null; then
    echo "CONTRIBUTING.mdの生成"

    # contributing.mdファイルの生成
    bash docs/script/gen-contribut

    # 変更をステージング
    find docs -type f -name "*.md" -print0 | xargs -0 git add --
    git add CONTRIBUTING.md
fi
