name: Linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: |
          clang-tidy solve/solve.cpp -- -std=c++20 -I.
